create table
    public.games
(
    id_game    bigint generated by default as identity,
    game_place character varying           not null,
    game_date  timestamp without time zone not null,
    constraint games_pkey primary key (id_game)
) tablespace pg_default;
create table
    public.player
(
    id_player        bigint generated by default as identity,
    name_player      text    not null,
    player_birthdate text    null,
    phone_player     text    null,
    password         text    not null,
    player_position  integer not null,
    username         text    not null,
    team_name        text    not null,
    team_id          bigint  null,
    constraint player_pkey primary key (id_player),
    constraint player_username_key unique (username)
) tablespace pg_default;

create table
    public.autorisation
(
    id_player bigint generated by default as identity,
    username  character varying not null,
    password  character varying not null,
    constraint autorisation_pkey primary key (id_player),
    constraint autorisation_id_player_fkey foreign key (id_player) references player (id_player) on update restrict on delete restrict,
    constraint autorisation_username_fkey foreign key (username) references player (username) on update cascade on delete cascade
) tablespace pg_default;

create table
    public.statistic
(
    id_person           bigint generated by default as identity,
    goals_aim           text not null default '0'::text,
    goals_current       text not null default '0'::text,
    pass_aim            text not null default '0'::text,
    pass_current        text not null default '0'::text,
    power_aim           text not null default '0'::text,
    power_current       text not null default '0'::text,
    catching_aim        text not null default '0'::text,
    catching_current    text not null default '0'::text,
    team_points_aim     text not null default '0'::text,
    team_points_current text not null default '0'::text,
    constraint statistic_pkey primary key (id_person),
    constraint statistic_id_person_key unique (id_person),
    constraint statistic_id_person_fkey foreign key (id_person) references player (id_player) on update restrict on delete restrict
) tablespace pg_default;

create table
    public.team
(
    id_team       bigint generated by default as identity,
    name_team     text    not null,
    players_count integer not null default 0,
    games_count   integer not null default 0,
    wins_count    integer not null default 0,
    constraint team_pkey primary key (id_team),
    constraint team_name_team_key unique (name_team)
) tablespace pg_default;

create table
    public.team_games
(
    id_game     bigint generated by default as identity,
    id_team_1   bigint not null,
    id_team_2   bigint not null,
    winner_team bigint not null,
    constraint team_games_pkey primary key (id_game),
    constraint team_games_id_game_fkey foreign key (id_game) references games (id_game) on update restrict on delete restrict,
    constraint team_games_id_team_1_fkey foreign key (id_team_1) references team (id_team),
    constraint team_games_id_team_2_fkey foreign key (id_team_2) references team (id_team),
    constraint team_games_winner_team_fkey foreign key (winner_team) references team (id_team)
) tablespace pg_default;

create table
    public.team_player
(
    id_team         bigint  not null,
    id_player       bigint  not null,
    player_position integer not null,
    id              bigint generated by default as identity,
    constraint team_player_pkey primary key (id_player, id),
    constraint team_player_id_player_fkey foreign key (id_player) references player (id_player) on update restrict on delete restrict
) tablespace pg_default;